apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fox-scaler
  namespace: default
  labels:
    app: fox
spec:
  scaleTargetRef:
    name: fox-app
  pollingInterval: 10  # Check metric every 10 seconds
  cooldownPeriod: 30   # Scale down after 30 seconds of inactivity
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: metrics-api
      metadata:
        scalerAddress: http://counter-service.default.svc.cluster.local:80/
        metricName: foxes
        value: "5"  # Scale up when `count` exceeds 5
