apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.counter.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: fox-service
spec:
  selector:
    app: fox
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.fox.port }}
