counter:
  name: counter-service
  image: ybello/counter-service:latest
  replicas: 1
  port: 8000
  metricEndpoint: http://counter-service.default.svc.cluster.local:80/

fox:
  name: fox-app
  image: nginx
  replicas: 1
  port: 80

scaling:
  threshold: 5
