apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter
spec:
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
